---
title: "Exercise1"
author: "Xinyi Jiang"
date: "2024-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 first function
```{r first function}
#define a simple function that takes a dataset as input
transform_data <- function(data) {
  #add 1 to each element in the dataset
  transformed_data <- data + 1
  return(transformed_data)
}

#test the function with the built-in dataset 'cars'
result1 <- transform_data(cars)
result1
```

## 2 generate an HTML file
   rmarkdown::render("C:/Users/16607/Local/Exercise1/Exercise1.Rmd")

```{bash}
git add Exercise1.Rmd Exercise1.html
git commit -m "add first simple function adn HTML output"
git push origin main
```

## 3 second function
```{bash}
git checkout -b dev
```

```{r second function}
#define a second simple function that takes a dataset as input
transform_data_v2 < - function(data) {
  #subtract 1 from each element in the dataset
  transform_data_v2 < - data - 1
  return(transformed_data_v2)
}
# Test the function with the built-in dataset 'cars'
result2 <- transform_data_v2(cars)
result2
```



